### ISSUE TITLE
Question on novel view synthesis

### ISSUE THREAD

**Issue by Beastmaster** [esdolo/FreeVS#3] opened 2024-11-14 05:20 UTC
Hi, thanks for you impressive work!
I have some questions on novel view synthesis.
1. I didn't see any point cloud stitching operation, so I assume that you perform projection within the same frame. When training, do you project the color-points in the same frame to test views?
2. durinig inference, how to decide which point cloud to use to perform projection? The appearance of point cloud projection image will change according to pose, I don't know how do you alleviate the mismatching appearance.

Best,

**Comment by esdolo** [comment] 2024-12-02 01:26
1. as shown in Fig.2, we project the lidar points in source frame T to supervision frame T+-k.
2. (1) we project points in the respective frame T to test views in frame T.    (2) The information loss caused by viewpoint transformation can not be fixed by some point cloud pre-processing. We rely on the generalization capability of the generative model to overcome the gap between original views and test views. The inpainting-like formulation of FreeVS and the viewpoint transformation simulation trick are key techniques to achieve this.  You may want to check Fig.B in the appendix, which shows how the generative model fixes the mismatching appearance in pseudo-images.

**Closed by esdolo** 2024-12-02 01:26 UTC
